### ISSUE TITLE
Support's Volume

### ISSUE THREAD

**Issue by agen49** [sameer/orient-stl#3]
Hello, 

Thank you for making your work available to public. 

How did you calculate/estimate the volume of supports? Can you post your code here for that part only?

Cheers!

**Comment by sameer** [comment]
Hi,

The problem this program solves might not be all that practical, but it is a good approximation.

It seeks to find the part orientation that minimizes the total surface area of overhang when projected onto the build plate. It does NOT consider any supports, that is discussed in the paper.

**Comment by sameer** [comment]
Closing due to age
